# Generated by Django 2.2.6 on 2019-10-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatexData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classification', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=50)),
                ('image_url', models.CharField(blank=True, max_length=300, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('features', models.TextField(blank=True, null=True)),
                ('tech_url', models.CharField(blank=True, max_length=300, null=True)),
                ('security_url', models.CharField(blank=True, max_length=300, null=True)),
                ('bar_code', models.CharField(max_length=50)),
            ],
        ),
    ]
